# First, config.yaml
name: "Tolgee"
version: "1.0"
slug: "tolgee"
description: "Self-hosted Tolgee localization platform"
url: "https://github.com/gijsvdhoven/homeassistant-addons/tree/main/tolgee"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8080
panel_icon: mdi:translate
init: false
ports:
  "8080/tcp": 8085
ports_description:
  "8080/tcp": "Web interface"
options:
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  ssl: bool
  certfile: str
  keyfile: str
map:
  - ssl
volumes:
  tolgee_data:
    name: tolgee_data
    driver: local
image: gijsvdhoven/{arch}-addon-homeassistant-tolgee
