name: "AppFlowy"
version: "1.0.0"
slug: "appflowy"
description: "Self-hosted AppFlowy instance"
url: "https://github.com/yourusername/ha-addons/tree/main/appflowy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
panel_icon: mdi:note-text
init: false
map:
  - share:rw
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": "Web interface"
devices:
  - /dev/dri
environment:
  DISPLAY: ":0"
volumes:
  appflowy-data:
    name: appflowy-data
    driver: local
